
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Request Calendar permission (shows one-time macOS popup).
 * Returns "granted", "denied", or an error message.
 */
async calendarAuthorize() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_authorize") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get events happening right now.
 */
async calendarGetCurrentMeeting() : Promise<Result<CalendarEventItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_get_current_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get calendar events in a time window.
 */
async calendarGetEvents(hoursBack: number | null, hoursAhead: number | null) : Promise<Result<CalendarEventItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_get_events", { hoursBack, hoursAhead }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset TCC (privacy) permission for Calendars on this app's bundle ID.
 *
 * Why: multiple users (including Louis's own Mac mini) clicked
 * "Fix Calendar Permission" → macOS opened the Calendars privacy pane
 * with an EMPTY app list, so they had no way to grant access. Root cause
 * is a stale TCC record (dev-build → prod-build reinstall, OS update,
 * user previously revoked etc.) where macOS silently refuses to re-add
 * the app on subsequent requestFullAccessToEventsWithCompletion calls.
 *
 * `tccutil reset Calendars <bundle_id>` clears that stale record. Next
 * call to requestFullAccessToEventsWithCompletion then shows the native
 * consent popup again and registers the app in Privacy → Calendars.
 *
 * Bundle ID is read at runtime from the running app (not hard-coded), so
 * this works for both `screenpi.pe` (prod) and `screenpi.pe.dev` (dev).
 * No sudo required — tccutil's per-app user scope is user-writable.
 */
async calendarResetPermission() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_reset_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check Calendar authorization status (no popup).
 */
async calendarStatus() : Promise<Result<CalendarStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check only accessibility permission
 * Use this for polling to check if user has granted accessibility permission
 */
async checkAccessibilityPermissionCmd() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_accessibility_permission_cmd");
},
/**
 * Check if Automation permission for Arc is already granted.
 * In production (.app bundle): uses direct FFI check (correct identity, no Terminal).
 * In dev mode: runs the binary itself via launchctl (detached from Terminal) so
 * macOS TCC checks the binary's own identity, not Terminal's.
 */
async checkArcAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_arc_automation_permission");
},
/**
 * Check if Arc browser is installed (macOS only)
 */
async checkArcInstalled() : Promise<boolean> {
    return await TAURI_INVOKE("check_arc_installed");
},
/**
 * Check if Automation permission is granted for all installed Chromium browsers.
 * Returns true only if ALL installed browsers have automation granted.
 */
async checkBrowsersAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_browsers_automation_permission");
},
/**
 * Returns true on macOS 14.4+ where the CoreAudio Process Tap API is
 * available. Used to gate the "experimental System Audio via CoreAudio"
 * toggle — we don't show it on platforms where flipping it would be a
 * no-op. False on Windows, Linux, and older macOS.
 */
async checkCoreaudioProcessTapAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_coreaudio_process_tap_available");
},
/**
 * Check Input Monitoring permission (macOS only).
 *
 * Input Monitoring is a TCC category separate from Accessibility. Without
 * it the recorder can still capture clipboard (via NSPasteboard polling)
 * and app/window switches, but not keystrokes or clicks. Polling-safe —
 * uses the preflight variant that doesn't trigger the system prompt.
 */
async checkInputMonitoringPermissionCmd() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_input_monitoring_permission_cmd");
},
/**
 * Check only microphone permission (no screen recording check)
 * Use this for polling to avoid triggering macOS screen capture permission dialogs
 */
async checkMicrophonePermission() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_microphone_permission");
},
async checkPermission(permission: OSPermission) : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_permission", { permission });
},
/**
 * Check only screen recording permission (no dialog trigger)
 * Uses CGPreflightScreenCaptureAccess which is safe to poll repeatedly
 */
async checkScreenRecordingPermission() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("check_screen_recording_permission");
},
async closeWindow(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOnboarding() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark the current app run as explicitly cleared to read browser Safe Storage.
 * Used by the owned-browser cookie menu's enable-and-retry action so the next
 * navigate can proceed to the macOS Keychain prompt without showing a second
 * in-app confirmation card.
 */
async confirmBrowserCookieAccessForSession() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_browser_cookie_access_for_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy a frame deeplink (screenpipe://frame/N) to clipboard. Native API only.
 */
async copyDeeplinkToClipboard(frameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_deeplink_to_clipboard", { frameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy a frame image to the system clipboard (native API, works in Tauri webview).
 * Fetches the frame from the local server and uses arboard for clipboard access.
 */
async copyFrameToClipboard(frameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_frame_to_clipboard", { frameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy arbitrary text to the system clipboard (native API, works in Tauri webview).
 * Use this instead of navigator.clipboard.writeText() which fails after async operations.
 */
async copyTextToClipboard(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_text_to_clipboard", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCacheFiles(paths: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cache_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disableKeychainEncryption() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_keychain_encryption") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable click-through mode on the main overlay window (Windows only)
 * When disabled, the overlay receives mouse events normally
 */
async disableOverlayClickThrough() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_overlay_click_through") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async doPermissionsCheck(initialCheck: boolean) : Promise<OSPermissionsCheck> {
    return await TAURI_INVOKE("do_permissions_check", { initialCheck });
},
/**
 * E2E helper: emit a deterministic chat stream from the Rust side.
 *
 * This keeps chat performance tests close to production's Pi stdout path:
 * one backend command starts the stream, then the app emits `agent_event`
 * envelopes into the WebView. Tests avoid the extra WebView→Rust→WebView
 * bridge hop that would come from calling `plugin:event|emit` for every token.
 */
async e2eEmitAgentStream(sessionId: string, deltaCount: number) : Promise<Result<E2eAgentStreamResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("e2e_emit_agent_stream", { sessionId, deltaCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * E2E helper: report whether the main overlay is logically visible.
 *
 * The main window uses platform-specific "hide" semantics (macOS NSPanel with
 * alpha=0, Windows/Linux hidden WebviewWindow). Tests need a stable signal that
 * the overlay has been dismissed when opening other surfaces (e.g. search).
 */
async e2eMainOverlayVisible() : Promise<boolean> {
    return await TAURI_INVOKE("e2e_main_overlay_visible");
},
/**
 * E2E-only probe: whether the owned-browser native webview is currently shown.
 * Mirrors `e2e_main_overlay_visible` — internal visibility state stays hidden
 * in production binaries and is only exposed under the `e2e` feature. Used by
 * `zz-owned-browser-background-nav.spec.ts` to assert a background agent/pipe
 * navigation does not reveal the browser over a non-chat view.
 */
async e2eOwnedBrowserVisible() : Promise<boolean> {
    return await TAURI_INVOKE("e2e_owned_browser_visible");
},
/**
 * E2E helper: report whether the shortcut reminder overlay is visibly shown.
 *
 * The reminder window is hidden rather than destroyed, so WebDriver can keep a
 * stale handle after users disable it from Settings > Display.
 */
async e2eShortcutReminderVisible() : Promise<boolean> {
    return await TAURI_INVOKE("e2e_shortcut_reminder_visible");
},
async enableKeychainEncryption() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_keychain_encryption") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable click-through mode on the main overlay window (Windows only)
 * When enabled, mouse events pass through to windows below
 */
async enableOverlayClickThrough() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_overlay_click_through") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-assert the WKWebView as first responder for the current key panel.
 * Called from JS on pointer enter / window focus to ensure trackpad pinch
 * gestures (magnifyWithEvent:) reach the WKWebView for zoom handling.
 */
async ensureWebviewFocus() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_webview_focus") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a recording to `output_path` (an .mp4).
 *
 * Pass `meeting_id` to export a meeting (its window is resolved from the DB),
 * or `start`/`end` for an arbitrary range (`end` defaults to now). Times accept
 * ISO 8601 or relative (`"2h ago"`, `"now"`). Returns a summary on success.
 */
async exportRecording(meetingId: number | null, start: string | null, end: string | null, outputPath: string) : Promise<Result<MeetingExportSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_recording", { meetingId, start, end, outputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force-regenerate suggestions immediately, bypassing the scheduler's
 * CPU/power guards. Returns the fresh suggestions and updates the cache.
 */
async forceRegenerateSuggestions() : Promise<Result<CachedSuggestions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("force_regenerate_suggestions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the macOS bundle identifier of the running app
 * (e.g. `screenpi.pe`, `screenpi.pe.beta`, or `screenpi.pe.dev`). The
 * onboarding stuck-screen surfaces this so
 * users who switched build channels (prod ↔ beta ↔ dev) can see they're
 * looking at a *different* TCC record from the one they may have already
 * granted under a sibling bundle id.
 */
async getAppIdentifier() : Promise<string> {
    return await TAURI_INVOKE("get_app_identifier");
},
/**
 * Get the app-local focus/notification server port.
 */
async getAppServerConfig() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_app_server_config");
},
async getAudioDevices() : Promise<Result<AudioDeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current boot phase of the server. Used by the onboarding UI to
 * show progress ("updating database", ...) while the HTTP
 * server is not yet listening — in particular during long DB migrations
 * where /health is unreachable.
 */
async getBootPhase() : Promise<BootPhaseSnapshot> {
    return await TAURI_INVOKE("get_boot_phase");
},
/**
 * Read the current runtime value of the global cookie-access flag.
 * Frontend calls this on startup to hydrate the AtomicBool from the
 * persisted store value.
 */
async getBrowserCookieAccessGranted() : Promise<boolean> {
    return await TAURI_INVOKE("get_browser_cookie_access_granted");
},
/**
 * Returns per-browser automation permission status for all installed Chromium browsers.
 */
async getBrowsersAutomationStatus() : Promise<BrowserAutomationStatus[]> {
    return await TAURI_INVOKE("get_browsers_automation_status");
},
/**
 * Return cached suggestions. If cache is empty (first load), generate
 * template suggestions from current activity data so the UI is never generic.
 */
async getCachedSuggestions() : Promise<Result<CachedSuggestions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cached_suggestions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiskUsage(forceRefresh: boolean | null, dataDir: string | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_disk_usage", { forceRefresh, dataDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns which E2E seeds are requested (env SCREENPIPE_E2E_SEED, comma-separated).
 * Rust uses "onboarding" in setup to complete onboarding at startup.
 */
async getE2eSeedFlags() : Promise<string[]> {
    return await TAURI_INVOKE("get_e2e_seed_flags");
},
async getEnv(name: string) : Promise<string> {
    return await TAURI_INVOKE("get_env", { name });
},
async getHardwareCapability() : Promise<HardwareCapability> {
    return await TAURI_INVOKE("get_hardware_capability");
},
/**
 * Returns the names of installed Chromium browsers that need Automation permission
 */
async getInstalledBrowsers() : Promise<string[]> {
    return await TAURI_INVOKE("get_installed_browsers");
},
async getKeychainStatus() : Promise<Result<KeychainStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_keychain_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the local API auth key and port for the frontend to use.
 * Returns the local API config (key, port, auth flag).
 *
 * IMPORTANT: This is `async` so it runs on the tokio thread pool, NOT the
 * main thread. The webview calls this via IPC during early init — if it ran
 * on the main thread it would deadlock with tray/window setup that also
 * needs the main thread, causing a 5-second blank screen.
 */
async getLocalApiConfig() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_local_api_config");
},
async getLogFiles() : Promise<Result<LogFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaFile(filePath: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check all permissions and return which ones are missing
 */
async getMissingPermissions() : Promise<OSPermission[]> {
    return await TAURI_INVOKE("get_missing_permissions");
},
async getMonitors() : Promise<Result<MonitorDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_monitors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnboardingStatus() : Promise<Result<OnboardingStore, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify explicitly provisioned PII model files. This command is read-only
 * and cannot initiate a network request.
 */
async getPiiModelStatus() : Promise<Result<PiiModelStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pii_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<void> {
    await TAURI_INVOKE("hide_main_window");
},
async hideNotificationPanel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_notification_panel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideShortcutReminder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_shortcut_reminder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy a skill folder into the screenpipe store. `source_path` is the folder
 * that directly contains `SKILL.md` (from a scan result or the folder picker).
 * Re-importing the same name refreshes it.
 */
async importSkill(sourcePath: string) : Promise<Result<ImportedSkill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_skill", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if click-through is currently enabled (Windows only)
 */
async isOverlayClickThrough() : Promise<boolean> {
    return await TAURI_INVOKE("is_overlay_click_through");
},
async isServerRunning() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_server_running") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCacheFiles() : Promise<Result<CacheFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_cache_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List skills currently in the screenpipe store.
 */
async listImportedSkills() : Promise<Result<ImportedSkill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_imported_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextAnalyze(imagePath: string, frameId: string, x: number, y: number, w: number, h: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_analyze", { imagePath, frameId, x, y, w, h }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextClearHighlights() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_clear_highlights") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextHide() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextHighlight(terms: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_highlight", { terms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextInit(windowLabel: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_init", { windowLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextIsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_is_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prefetch VisionKit analysis for adjacent frames in the background.
 * Fire-and-forget — results are cached in Swift for instant hits later.
 */
async livetextPrefetch(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_prefetch", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Place a transparent click guard above the Live Text overlay in the given
 * rectangle (web/CSS coordinates: origin top-left). Each guard is identified
 * by a string key (e.g. "navbar", "filters", "scrubber"). This prevents
 * VisionKit's text-selection hit regions from intercepting clicks on UI controls.
 */
async livetextSetGuardRect(key: string, x: number, y: number, w: number, h: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_set_guard_rect", { key, x, y, w, h }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async livetextUpdatePosition(frameId: string, x: number, y: number, w: number, h: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("livetext_update_position", { frameId, x, y, w, h }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a local markdown note in Obsidian (if available), then fallback to OS default app.
 */
async openNotePath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_note_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPermissionSettings(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { permission });
},
async openSearchWindow(query: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_search_window", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the viewer window for `path`. Reuses an existing window if one
 * for the same path is already open.
 */
async openViewerWindow(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_viewer_window", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openWindowsShellTarget(target: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_windows_shell_target", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all browsing data for the owned-browser webview: cookies, injected
 * cookies, site storage, and cache. This resets the current shared owned
 * browser slate; per-chat isolation belongs to the follow-up PR.
 */
async ownedBrowserClearBrowsingData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("owned_browser_clear_browsing_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the embedded webview without destroying it. Equivalent to calling
 * `set_bounds` with zero dimensions, but more explicit at the call site.
 */
async ownedBrowserHide() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("owned_browser_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate the embedded webview to `url`. Used by the sidebar when restoring
 * per-chat state or on user reload — i.e. always an action of the chat that's
 * on screen, so it carries no owner (`None`) and the frontend always honors
 * it. The agent/pipe path is the connect-trait `navigate` (owner-tagged).
 */
async ownedBrowserNavigate(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("owned_browser_navigate", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ownedBrowserResolveSessionAccess(requestId: string, allow: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("owned_browser_resolve_session_access", { requestId, allow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Position and size the embedded child webview. The frontend sends
 * viewport-relative coords from the same window that hosts the child, so
 * they can be applied as parent-local bounds. Call with width/height = 0
 * to hide.
 */
async ownedBrowserSetBounds(parent: string, x: number, y: number, width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("owned_browser_set_bounds", { parent, x, y, width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Perform OCR on a base64-encoded PNG image crop, using the user's configured OCR engine.
 */
async performOcrOnImage(imageBase64: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_ocr_on_image", { imageBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort current Pi operation. Priority command — cancels all pending commands
 * in the queue and sends abort directly. Waits for the SDK's done event.
 */
async piAbort(sessionId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_abort", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort only the active Pi operation. Pending queued follow-ups remain queued.
 */
async piAbortActive(sessionId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_abort_active", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a single queued prompt. Returns true if it was still in the queue
 * (and is now removed), false if it had already been pulled into the
 * in-flight slot — at that point `pi_abort` is the right tool.
 */
async piCancelQueued(sessionId: string | null, promptId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_cancel_queued", { sessionId, promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if pi is available
 */
async piCheck() : Promise<Result<PiCheckResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Pi info
 */
async piInfo(sessionId: string | null) : Promise<Result<PiInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_info", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install pi via bun
 */
async piInstall() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a new Pi session (clears conversation history).
 * Serialized through the queue — waits for any in-flight work to complete,
 * then sends new_session and waits for the SDK's done event before returning.
 */
async piNewSession(sessionId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_new_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current queued-prompt list for a session. Useful for an initial
 * render before the first `pi-queue-changed` event arrives, and for new
 * chat windows opening on top of an in-progress queue.
 */
async piPending(sessionId: string | null) : Promise<Result<PiQueuedPrompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_pending", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a prompt to Pi, optionally with images.
 * The command is serialized through the queue — it will wait for any prior
 * command (new_session, abort) to fully complete before being written to stdin.
 */
async piPrompt(sessionId: string | null, message: string, images: PiImageContent[] | null, displayPreview: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_prompt", { sessionId, message, images, displayPreview }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Queue a follow-up prompt for the current session. Unlike `pi_prompt`, this
 * returns as soon as Rust owns the queued item; the prompt is written only
 * after the active turn finishes.
 */
async piQueuePrompt(sessionId: string | null, message: string, images: PiImageContent[] | null, displayPreview: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_queue_prompt", { sessionId, message, images, displayPreview }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hot-swap Pi's active model without killing the subprocess. Preserves the
 * full conversation state in-place — the user can switch haiku ↔ sonnet ↔ opus
 * mid-session and the new model sees the real threaded history, not a
 * glued-transcript workaround.
 *
 * Pi's RPC `set_model` is the right path for provider+model changes only. If
 * other preset fields change (url, apiKey, maxTokens, systemPrompt) the
 * caller should fall back to `pi_update_config` which does a full restart
 * because those are spawn-time args baked into models.json / CLI flags.
 */
async piSetModel(sessionId: string | null, providerConfig: PiProviderConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_set_model", { sessionId, providerConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the Pi sidecar in RPC mode (Tauri command wrapper)
 */
async piStart(sessionId: string | null, projectDir: string, providerConfig: PiProviderConfig | null) : Promise<Result<PiInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_start", { sessionId, projectDir, providerConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Steer the active Pi reply using Pi's native steering command.
 * Unlike `pi_prompt`, this is intentionally not added to the follow-up queue:
 * Pi interrupts the current stream and resumes with the steering instruction.
 */
async piSteer(sessionId: string | null, message: string, images: PiImageContent[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_steer", { sessionId, message, images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Promote a queued follow-up into Pi's native steer path. The prompt is
 * removed from the Rust queue first, so it cannot later run as a normal
 * follow-up.
 */
async piSteerQueued(sessionId: string | null, promptId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_steer_queued", { sessionId, promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the Pi sidecar
 */
async piStop(sessionId: string | null) : Promise<Result<PiInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_stop", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update Pi config and restart the chat session so the new model takes effect.
 * Without restart, Pi keeps using the provider/model from its original CLI args.
 *
 * Prefer `pi_set_model` when only provider+model changed — it preserves the
 * conversation state instead of killing the subprocess.
 */
async piUpdateConfig(providerConfig: PiProviderConfig | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pi_update_config", { providerConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read bundle ID, display name, and icon from a `.app` bundle selected in Finder.
 */
async readAppBundleMetadata(path: string) : Promise<Result<ExcludedApp, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_app_bundle_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current exclusion list. Returns an empty Vec if the file is
 * missing, unreadable, or wrong-shape (matches engine fallback behavior).
 * Returns Err only for malformed JSON, so the UI can surface "your file
 * has a syntax error" to the user.
 */
async readAudioExclusions() : Promise<Result<ExcludedApp[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_audio_exclusions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a file for the viewer. Returns text for text-like files, a
 * base64 data URL for images. Files larger than `MAX_VIEWER_FILE_BYTES`
 * are truncated for text or refused for images, since both would blow
 * up the renderer.
 */
async readViewerFile(path: string) : Promise<Result<ViewerContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_viewer_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: re-encrypt store.bin after frontend saves.
 */
async reencryptStore() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reencrypt_store") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshTrayMenu() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_tray_menu") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wipe the persisted API auth key and write a fresh `sp-<uuid8>` to the
 * secret store. Returns the new key. The running server keeps its old key
 * in memory until restart — the UI should prompt the user to apply & restart.
 */
async regenerateApiAuthKey() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regenerate_api_auth_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register window-specific shortcuts (Escape, search shortcut) when main window is visible
 * These should only be active when the overlay is open to avoid blocking other apps
 */
async registerWindowShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_window_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a skill from the store. The pi executor's sync drops the mirrored
 * copies from new sessions; we also clear the chat agent's live copy so it
 * disappears without waiting for a restart.
 */
async removeImportedSkill(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_imported_skill", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request macOS Automation permission for Arc browser.
 * In production: triggers "screenpipe wants to control Arc" prompt via direct FFI.
 * In dev mode: runs the binary itself via launchctl to trigger the prompt with
 * the correct binary identity (not Terminal's). Also opens System Settings as fallback.
 */
async requestArcAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_arc_automation_permission");
},
/**
 * Request Automation permission for installed Chromium browsers that are already running.
 * Never force-launches browsers — only prompts for ones the user already has open.
 * Opens System Settings > Automation as fallback for browsers not running.
 */
async requestBrowsersAutomationPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_browsers_automation_permission");
},
/**
 * Request Input Monitoring permission (macOS only).
 *
 * Calls `cg_access::listen_request()` to trigger the system permission
 * flow. On first call this either shows the native prompt (if NotDetermined)
 * or silently no-ops (if already Denied — macOS doesn't re-prompt). For
 * reliability we also open System Settings → Input Monitoring so the user
 * can grant manually if the prompt didn't appear.
 *
 * Returns the post-request permission status so the UI can update without
 * waiting for the next poll.
 */
async requestInputMonitoringPermission() : Promise<OSPermissionStatus> {
    return await TAURI_INVOKE("request_input_monitoring_permission");
},
async requestPermission(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("request_permission", { permission });
},
/**
 * Request automation permission for a single browser by name.
 * Returns the new status: "granted", "denied", or "not_asked".
 */
async requestSingleBrowserAutomation(browserName: string) : Promise<string> {
    return await TAURI_INVOKE("request_single_browser_automation", { browserName });
},
/**
 * Reset a permission using tccutil and re-request it
 * This removes the app from the TCC database and triggers a fresh permission request
 */
async resetAndRequestPermission(permission: OSPermission) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_and_request_permission", { permission }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the Main panel so the next shortcut press reconfigures it for the new mode.
 */
async resetMainWindow() : Promise<void> {
    await TAURI_INVOKE("reset_main_window");
},
async resetOnboarding() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetPermission(permission: OSPermission) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_permission", { permission }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the Search NSPanel. Regular Tauri setSize doesn't work on NSPanels.
 */
async resizeSearchWindow(width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_search_window", { width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeGlobalShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_global_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal a file in the OS file browser (Finder / Explorer / etc).
 */
async revealInDefaultBrowser(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_default_browser", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan the standard locations for skill folders the user could import.
 */
async scanDeviceSkills() : Promise<Result<DeviceSkill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_device_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Navigate from Search to a timestamp on the Main timeline.
 * Shows Main, emits the navigation event from the app handle (not a webview),
 * then closes the Search window.
 */
async searchNavigateToTimeline(timestamp: string, frameId: number | null, searchTerms: string[] | null, searchResultsJson: string | null, searchQuery: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_navigate_to_timeline", { timestamp, frameId, searchTerms, searchResultsJson, searchQuery }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a user-supplied API auth key to the secret store.
 * The running server keeps its in-memory key until restart.
 */
async setApiAuthKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_auth_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostart(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the global browser cookie-access permission. Called from the
 * frontend when the user clicks "Use browser session" in the prompt card
 * or toggles the setting in the settings page.
 */
async setBrowserCookieAccessGranted(granted: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_browser_cookie_access_granted", { granted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hydrate/update the complete browser cookie access state. `granted=false`
 * with `disabled=false` means first-run unknown: prompt once if cookies exist.
 */
async setBrowserCookieAccessState(granted: boolean, disabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_browser_cookie_access_state", { granted, disabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNativeTheme(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_native_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboardingStep(step: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_step", { step }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrayHealthIcon() : Promise<void> {
    await TAURI_INVOKE("set_tray_health_icon");
},
async setTrayUnhealthIcon() : Promise<void> {
    await TAURI_INVOKE("set_tray_unhealth_icon");
},
/**
 * Programmatically adjust a window's always-on-top level after creation.
 *
 * Tauri's JS `setAlwaysOnTop` can be unreliable for macOS panel-style
 * windows. For permission flows we need Screenpipe to stay normally
 * always-on-top, but temporarily drop below System Settings while the user is
 * granting permissions. On macOS this directly sets the underlying NSWindow
 * level: floating when enabled, normal when disabled.
 */
async setWindowAlwaysOnTopNative(label: string, alwaysOnTop: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_always_on_top_native", { label, alwaysOnTop }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindowSize(window: ShowRewindWindow, width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_size", { window, width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindow() : Promise<void> {
    await TAURI_INVOKE("show_main_window");
},
async showNotificationPanel(payload: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_notification_panel", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOnboardingWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_onboarding_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showPermissionRecoveryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_permission_recovery_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showShortcutReminder(shortcut: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_shortcut_reminder", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showWindow(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Like `show_window` but forces macOS app activation first, so the target
 * window actually comes to the foreground when the caller is a
 * `NSNonactivatingPanelMask` panel (notifications, tray, etc.).
 *
 * Without this, clicking "Open" in the notification panel on macOS often
 * appears to do nothing: the non-activating panel style prevents the app
 * from becoming active, and overlay/fullscreen main modes rely on an
 * activate-aware `show_panel_visible(activate_app=true)` path that only
 * fires for `overlay_mode == "window"`. The window technically shows but
 * stays behind whatever app the user was in.
 *
 * Callers that represent explicit user intent (clicking Open on a
 * notification) should use this variant. Passive show-surface callers
 * should keep using `show_window` to avoid stealing focus unnecessarily.
 */
async showWindowActivated(window: ShowRewindWindow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window_activated", { window }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the server (if not running) and capture.
 * This is the main entry point called by the frontend.
 */
async spawnScreenpipe(overrideArgs: string[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_screenpipe", { overrideArgs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start recording. Requires the server to be running.
 */
async startCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop recording without killing the server.
 * Memories, search, and the HTTP API remain accessible.
 */
async stopCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop capture AND server so the next spawn_screenpipe does a full restart.
 * Called by "Apply & Restart" and audio shortcuts.
 * The tray toggle uses stop_capture / start_capture to keep the server alive.
 */
async stopScreenpipe() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_screenpipe") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suspendGlobalShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_global_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: start voice training. Spawns a background task that polls
 * until audio is transcribed, then assigns the speaker. Returns immediately.
 */
async trainVoice(name: string, startTime: string, endTime: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("train_voice", { name, startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unregister window-specific shortcuts when main window is hidden.
 * Only unregisters Escape and arrow keys. Global shortcuts (search, show, chat)
 * are NOT touched here — they must persist across window show/hide cycles.
 */
async unregisterWindowShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_window_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGlobalShortcuts(showShortcut: string, startShortcut: string, stopShortcut: string, startAudioShortcut: string, stopAudioShortcut: string, profileShortcuts: { [key in string]: string }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_global_shortcuts", { showShortcut, startShortcut, stopShortcut, startAudioShortcut, stopAudioShortcut, profileShortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateShowScreenpipeShortcut(newShortcut: string, enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_show_screenpipe_shortcut", { newShortcut, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: validate that a path is usable as a data directory.
 * Called from the frontend before saving the setting.
 */
async validateDataDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_data_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check vault lock state from filesystem (no server needed).
 */
async vaultStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fast unlock: verify password, decrypt DB only, remove sentinel.
 * Data files are decrypted in background — server can start immediately.
 */
async vaultUnlock(password: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_unlock", { password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write the exclusion list atomically (write-to-tmp + rename) so the
 * engine's 500 ms mtime poll never observes a half-written file. The
 * engine picks up the new list on the next tick subject to its
 * `REBUILD_COOLDOWN` (60 s).
 */
async writeAudioExclusions(apps: ExcludedApp[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_audio_exclusions", { apps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeBrowserLog(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("write_browser_log", { level, message });
},
async writeBrowserLogs(entries: BrowserLogEntry[]) : Promise<void> {
    await TAURI_INVOKE("write_browser_logs", { entries });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AIPreset = { id: string; prompt: string; provider: AIProviderType; url?: string; model?: string; defaultPreset: boolean; apiKey: string | null; maxContextChars: number; maxTokens?: number }
export type AIProviderType = "native-ollama"
export type AudioDeviceInfo = { name: string; isDefault: boolean }
export type BootPhaseSnapshot = {
/**
 * One of: idle | starting | migrating_database | building_audio | ready | error
 */
phase: string;
/**
 * Human-readable detail to show the user (may be long-running hint)
 */
message: string | null;
/**
 * Present only when phase == "error"
 */
error: string | null;
/**
 * Unix epoch seconds when the current phase was entered. Lets the UI
 * show "X minutes" on slow migrations.
 */
sinceEpochSecs: number }
/**
 * Per-browser automation status: "granted", "denied", or "not_asked".
 * Also includes whether the browser is currently running.
 */
export type BrowserAutomationStatus = { name: string; status: string; running: boolean }
export type BrowserLogEntry = { level: string; message: string }
export type CacheFile = { path: string; label: string; size_bytes: number }
export type CachedSuggestions = { suggestions: Suggestion[]; generatedAt: string; mode: string; aiGenerated: boolean; tags: string[] }
export type CalendarEventItem = { id: string; title: string;
/**
 * RFC3339 in UTC — for meeting detection / comparisons.
 */
start: string;
/**
 * RFC3339 in UTC — for meeting detection / comparisons.
 */
end: string;
/**
 * Pre-formatted local time, e.g. "3:30 PM" — for display.
 */
startDisplay: string;
/**
 * Pre-formatted local time, e.g. "5:00 PM" — for display.
 */
endDisplay: string; attendees: string[]; location: string | null; meetingUrl: string | null; calendarName: string; isAllDay: boolean;
/**
 * Source identifier: "native" for OS calendar, "ics" for ICS feeds.
 * Used by meeting detector to merge events from multiple publishers.
 */
source?: string }
export type CalendarStatus = { available: boolean; authorized: boolean; authorizationStatus: string; calendarCount: number }
/**
 * A skill folder discovered somewhere on the user's device.
 */
export type DeviceSkill = {
/**
 * Display name (from frontmatter `name:`, falling back to the folder name).
 */
name: string;
/**
 * One-line summary from frontmatter `description:` (may be empty).
 */
description: string;
/**
 * Absolute path to the skill folder (the one containing `SKILL.md`).
 */
path: string;
/**
 * Human label for where it was found, e.g. `~/.claude/skills`.
 */
source: string;
/**
 * True when a skill of the same normalized name is already imported.
 */
imported: boolean }
export type E2eAgentStreamResult = { emitted_deltas: number; emit_ms: number }
export type EmbeddedLLM = { enabled: boolean; model: string; port: number }
export type ExcludedApp = { bundleId: string; name: string | null; icon: string | null }
export type HardwareCapability = { hasGpu: boolean; cpuCores: number; totalMemoryGb: number; recommendedEngine: string; reason: string }
/**
 * A skill currently sitting in the screenpipe store.
 */
export type ImportedSkill = { name: string; description: string;
/**
 * Absolute path inside `<data_dir>/skills/`.
 */
path: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type KeychainStatus = { state: string }
export type LogFile = { name: string; path: string; modified_at: number }
export type MeetingExportSummary = { output_path: string; frame_count: number; audio_chunk_count: number; duration_secs: number; file_size_bytes: number }
export type MonitorDevice = { id: number; stableId: string; name: string; isDefault: boolean; width: number; height: number }
export type OSPermission = "screenRecording" | "microphone" | "accessibility" | "automation" | "inputMonitoring" | "calendar"
export type OSPermissionStatus = "notNeeded" | "empty" | "granted" | "denied"
export type OSPermissionsCheck = { screenRecording: OSPermissionStatus; microphone: OSPermissionStatus; accessibility: OSPermissionStatus }
export type OnboardingStore = { isCompleted: boolean; completedAt: string | null;
/**
 * Current step in onboarding flow (login, intro, usecases, status)
 * Used to resume after app restart (e.g., after granting permissions)
 */
currentStep?: string | null }
export type PiCheckResult = { available: boolean; path: string | null }
/**
 * Image content for Pi RPC protocol (pi-ai ImageContent format)
 */
export type PiImageContent = { type: string; mimeType: string; data: string }
export type PiInfo = { running: boolean; projectDir: string | null; pid: number | null; sessionId: string | null }
/**
 * Configuration for which AI provider Pi should use
 */
export type PiProviderConfig = {
/**
 * Local Ollama model ID to use.
 */
model: string;
/**
 * Max output tokens (default 4096)
 */
maxTokens?: number;
/**
 * Optional system prompt from AI preset (appended to Pi's built-in system prompt)
 */
systemPrompt?: string | null }
/**
 * A user prompt that's been enqueued but not yet written to Pi's stdin.
 * Surfaced to the UI so the chat can render "queued" cards while a prior
 * prompt is still streaming. Once the queue's drain loop pulls a prompt and
 * writes it to stdin, the entry is removed (it's now in-flight, not queued).
 */
export type PiQueuedPrompt = {
/**
 * Stable id assigned at enqueue time. Used to remove the entry on
 * dequeue / abort / write-failure.
 */
id: string;
/**
 * First ~200 chars of the user message — enough for the UI to show a
 * readable preview without round-tripping the full prompt over IPC.
 */
preview: string;
/**
 * Unix epoch milliseconds for "queued at" — drives the relative-time
 * label in the UI ("queued 4s ago").
 */
queuedAtMs: number }
export type PiiModelFileStatus = { name: string; path: string; sourceUrl: string; expectedSha256: string; actualSha256: string | null; state: string }
export type PiiModelStatus = { textReady: boolean; imageReady: boolean; textDirectory: string; imageDirectory: string; textFiles: PiiModelFileStatus[]; imageFiles: PiiModelFileStatus[] }
/**
 * A single schedule rule: a day-of-week + time range + what to record.
 */
export type ScheduleRule = {
/**
 * Day of week: 0 = Monday, 6 = Sunday
 */
dayOfWeek: number;
/**
 * Start time in "HH:MM" (24h format, local time)
 */
startTime: string;
/**
 * End time in "HH:MM" (24h format, local time)
 */
endTime: string;
/**
 * What to record: "all", "audio_only", "screen_only"
 */
recordMode: string }
export type SettingsStore =
/**
 * All recording/capture config lives here. Flattened so the JSON shape
 * is unchanged — `disableAudio`, `port`, `fps`, etc. stay at the top level.
 */
({
/**
 * Disable all audio capture and transcription.
 */
disableAudio: boolean;
/**
 * Audio transcription engine identifier.
 *
 * The persisted value is intentionally a string for compatibility with
 * existing `store.bin` files. Unsupported or retired values are resolved
 * to a local engine by [`Self::local_audio_transcription_engine`] before
 * capture starts.
 */
audioTranscriptionEngine: string;
/**
 * Transcription mode: "realtime" or "batch".
 * Previously stored in SettingsStore.extra["transcriptionMode"].
 */
transcriptionMode: string;
/**
 * Stream live notes only for manually-started live meetings. This is
 * separate from 24/7 background transcription: the recorder still writes
 * durable chunks, while this powers the low-latency meeting note UI.
 */
meetingLiveTranscriptionEnabled: boolean;
/**
 * Provider for manually-started live notes. Defaults to the selected audio
 * transcription engine so local/custom engines work without Cloud.
 */
meetingLiveTranscriptionProvider: string;
/**
 * Audio device names/IDs to capture from.
 */
audioDevices: string[];
/**
 * Automatically follow the system default audio devices.
 */
useSystemDefaultAudio: boolean;
/**
 * Experimental: capture System Audio via the CoreAudio Process Tap API
 * (macOS 14.4+) instead of ScreenCaptureKit. The tap sidesteps SCK's
 * display-enumeration failures after sleep/wake and the GPU/compositor
 * wake overhead, but it cannot see audio rendered through a
 * VoiceProcessing AudioUnit (Zoom / Google Meet / Microsoft Teams all
 * use one for echo cancellation), so on meeting audio it silently
 * captures zeroed buffers even though tap creation succeeds.
 *
 * Default `false` (see `default_experimental_coreaudio_system_audio`).
 * SCK captures at the display compositor, which does see VoiceProcessing
 * output, so it is the right default for anyone on calls. Users who hit
 * SCK's sleep/wake display-enumeration bug can still opt in; when the tap
 * is on and creation fails (permission, macOS <14.4, OS quirk), stream.rs
 * falls back to the SCK path automatically. Ignored on non-macOS platforms.
 */
experimentalCoreaudioSystemAudio?: boolean;
/**
 * Experimental: request Windows WASAPI microphone Acoustic Echo Cancellation.
 * Ignored on non-Windows platforms and fail-open when unsupported by device/driver.
 */
windowsInputAecEnabled?: boolean;
/**
 * Experimental: request Apple VoiceProcessingIO (AEC) on the default macOS microphone.
 * Ignored on non-macOS platforms. Only the system default input uses VPIO; other devices use HAL.
 */
macosInputVpioEnabled?: boolean;
/**
 * Duration of each audio chunk in seconds before transcription.
 * Stored as i32 to match existing store.bin schema (cast to u64 by engine).
 */
audioChunkDuration: number;
/**
 * Filter music-dominant audio before transcription using spectral analysis.
 */
filterMusic: boolean;
/**
 * Maximum batch duration in seconds for local batch transcription.
 * None uses the selected local engine's default.
 * Also controls the max deferral cap during active meetings.
 */
batchMaxDurationSecs?: number | null;
/**
 * Custom vocabulary for transcription biasing and word replacement.
 * Previously stored in SettingsStore.extra["vocabularyWords"].
 */
vocabularyWords?: VocabEntry[];
/**
 * Disable all screen capture.
 */
disableVision: boolean;
/**
 * Disable the timeline / rewind feature. When true, the engine skips
 * timeline-only work: warming the hot frame cache from the DB at startup
 * and buffering captured frames/audio into the in-memory hot cache that
 * only the timeline streaming endpoint reads.
 */
disableTimeline?: boolean;
/**
 * Specific monitor IDs to capture.
 */
monitorIds: string[];
/**
 * Capture from all connected monitors.
 */
useAllMonitors: boolean;
/**
 * Video quality preset: "low", "balanced", "high", "max".
 */
videoQuality: string;
/**
 * Maximum width for stored snapshots. Images wider than this are downscaled
 * (preserving aspect ratio) before JPEG encoding. 0 = no limit (store at
 * native resolution). Default: 1920.
 */
maxSnapshotWidth?: number;
/**
 * Skip the background JPEG->MP4 snapshot compaction worker.
 * Use when the MP4 timeline UI is not used, e.g. task-mining tools
 * that consume accessibility_text / ui_events only.
 * Side effect: JPEGs are not compacted, so disk usage depends on retention.
 */
disableSnapshotCompaction?: boolean;
/**
 * Skip the v2 meeting detector watcher (5s-interval process / AX scan).
 * Use when meeting detection is not consumed (task-mining, headless analysis,
 * agents that read accessibility_text and ui_events only) — avoids the
 * constant process enumeration + AX tree walk cost.
 * Side effect: meeting-related DB rows are not generated; the audio pipeline's
 * in_meeting override flag stays false.
 */
disableMeetingDetector?: boolean;
/**
 * Apps / meeting services to exclude from automatic meeting detection
 * while leaving detection on for everything else. Case-insensitive
 * substring match against the running app's name/process AND the matched
 * detection profile's identifiers (native names + browser URL patterns),
 * so an entry can be what the user sees ("Discord") or a service domain
 * ("meet.google.com"). Use when one app trips the detector spuriously
 * (an always-open Teams, a Discord call you don't want logged) but you
 * still want Zoom/Meet/etc. detected. Empty = detect all known apps.
 */
ignoredMeetingApps?: string[];
/**
 * Override `EventDrivenCaptureConfig::idle_capture_interval_ms` (milliseconds).
 * None = follow active PowerProfile.
 */
idleCaptureIntervalMs?: number | null;
/**
 * Override `EventDrivenCaptureConfig::visual_check_interval_ms` (milliseconds).
 * None = follow active PowerProfile.
 */
visualCheckIntervalMs?: number | null;
/**
 * Override `EventDrivenCaptureConfig::visual_change_threshold` (0.0–1.0).
 * None = follow active PowerProfile.
 */
visualChangeThreshold?: number | null;
/**
 * Override `EventDrivenCaptureConfig::min_capture_interval_ms` (milliseconds).
 * None = follow active PowerProfile.
 */
minCaptureIntervalMs?: number | null;
/**
 * Default behavior when a meeting is detected.
 * `"ask"` (default) surfaces a "+ HD" action on the existing meeting
 * notification; `"always"` auto-starts a meeting-bound HD session
 * every time; `"never"` is opt-out — only the manual tray timer
 * can start a session.
 *
 * Runtime-mutable via `POST /capture/hd/settings`; this field
 * just seeds the controller on startup.
 */
hdRecordingDefault?: string;
/**
 * Capture debounce (ms) installed while an HD session is active.
 * Default 100 ms ≈ 10 fps — smooth enough for human replay without
 * exploding disk usage. Clamped to >= 33 ms (30 fps ceiling) by the
 * controller.
 */
hdRecordingIntervalMs?: number;
/**
 * Legacy key-trigger override retained for settings compatibility.
 * Recording sessions keep keyboard-triggered capture on; raw key/text DB
 * rows are controlled separately by `disableKeyboardCapture`.
 */
captureOnKeystroke?: boolean | null;
/**
 * Override `EventDrivenCaptureConfig::capture_on_clipboard`.
 * None = engine default (false). When true, clipboard changes fire a
 * paired capture. Clipboard DB rows are still controlled separately by
 * `disableClipboardCapture`.
 */
captureOnClipboard?: boolean | null;
/**
 * Override `UiRecorderConfig::capture_scroll`.
 * None = engine default (false). When true, scroll wheel events are
 * recorded into `ui_events` so the `ScrollBurstTracker` can fire a
 * `ScrollStop` trigger at burst-end and link the last scroll row to
 * the resulting frame. Off by default — wheel ticks fire at ~60Hz
 * and inflate the table fast.
 */
captureScroll?: boolean | null;
/**
 * Prioritize mouse/keyboard input latency over a11y event completeness.
 * Opt-in master switch for the three coordinated optimizations defined on
 * `UiCaptureConfig.prioritize_input_latency`.
 */
prioritizeInputLatency?: boolean;
/**
 * OS thread priority for a11y extraction threads when `prioritize_input_latency`
 * is true. Values: "normal" / "below_normal" / "lowest" / "idle".
 */
extractionThreadPriority?: string;
/**
 * Skip UIA tree captures within this many ms after the most recent input.
 * 0 disables. Ignored when `prioritize_input_latency` is false.
 */
pauseExtractionOnInputMs?: number;
/**
 * Window titles to exclude from capture.
 */
ignoredWindows: string[];
/**
 * Window titles to exclusively capture (empty = capture all).
 */
includedWindows: string[];
/**
 * URLs to exclude from capture.
 */
ignoredUrls?: string[];
/**
 * Automatically detect and skip incognito / private browsing windows.
 */
ignoreIncognitoWindows: boolean;
/**
 * Experimental: pause screen capture when a DRM-protected streaming app
 * (Netflix, Disney+, etc.) or a remote-desktop client (Omnissa/VMware
 * Horizon) is focused. These apps blank their windows while screen
 * recording is active.
 * Off by default; engine-only pause (no full app shutdown).
 */
pauseOnDrmContent?: boolean;
/**
 * Skip persisting clipboard rows/content in the UI recorder. Defaults to
 * `true` (clipboard DB capture OFF) — passwords / API keys / private keys
 * frequently pass through the clipboard. Clipboard operations can still
 * wake event-driven capture when `captureOnClipboard` is enabled.
 */
disableClipboardCapture?: boolean;
/**
 * Skip persisting keyboard / typed-text rows in the UI recorder.
 * Defaults to `true` (keyboard DB capture OFF). Keyboard events still
 * wake event-driven capture, and the accessibility tree + OCR still
 * capture on-screen text so Rewind/Ask keep working.
 * Opt in to keyboard DB rows via the "Capture keyboard" toggle.
 */
disableKeyboardCapture?: boolean;
/**
 * Continue recording audio when the screen is locked.
 * Default: false (audio pauses when screen is locked to save resources).
 */
recordWhileLocked?: boolean;
/**
 * Languages for transcription (ISO 639-1 codes).
 */
languages: string[];
/**
 * Redact personally identifiable information from transcriptions.
 */
usePiiRemoval: boolean;
/**
 * Enable the async PII reconciliation worker. When `true`, a
 * background task runs after capture and OVERWRITES PII in the
 * source columns of `ocr_text`, `audio_transcriptions`,
 * `frames.accessibility_text`, and `ui_events.text_content`. Raw
 * secrets are gone after the worker processes the row — that's
 * the contract of the user-facing "AI PII removal" toggle.
 * Off by default; capture path is unaffected either way. See
 * `screenpipe-redact` for the full design.
 */
asyncPiiRedaction?: boolean;
/**
 * Enable image-PII redaction on captured screen frames. When
 * `true`, the `screenpipe_redact::image::worker` runs alongside
 * the text reconciliation worker, scans the `frames` table, runs
 * the RF-DETR-Nano detector, and blacks out detected PII regions
 * in each JPG (atomic overwrite of the source file). Off by
 * default — orthogonal to `async_pii_redaction` (text path),
 * independently togglable. Requires the `screenpipe-redact`
 * crate to be built with one of the `onnx-*` cargo features and
 * the checksum-verified `rfdetr_v12.onnx` model present at
 * `~/.screenpipe/models/`.
 */
asyncImagePiiRedaction?: boolean;
/**
 * Which PII classes the AI redaction workers actually rewrite
 * when `asyncPiiRedaction` / `asyncImagePiiRedaction` are on.
 * Canonical snake_case `SpanLabel` names (e.g.
 * `["secret", "email", "person"]`). The models detect every
 * class but only these are removed — the rest is *value* (a
 * searchable timeline). Defaults to `["secret"]`, the safety
 * baseline; `secret` is always treated as included regardless of
 * what's stored (see screenpipe-redact `parse_allow_list`). The
 * Settings UI surfaces a curated subset (Names, Emails, Phones,
 * Addresses, Sensitive) as opt-in checkboxes.
 */
piiRedactionLabels?: string[];
/**
 * Screenpipe cloud user ID. Empty string means not logged in.
 * Kept as String (not Option) to match existing store.bin schema.
 */
userId: string;
/**
 * Display name for speaker identification.
 * Fallback chain: this field → cloud auth name → cloud auth email.
 * Previously stored in SettingsStore.extra["userName"].
 */
userName?: string | null;
/**
 * HTTP server port for the screenpipe API.
 */
port: number;
/**
 * Power mode preference: "auto", "performance", "battery_saver".
 * Previously stored in SettingsStore.extra["powerMode"].
 */
powerMode?: string | null;
/**
 * Use Chinese mirror for Hugging Face model downloads.
 */
useChineseMirror: boolean;
/**
 * Detected hardware tier ("high", "mid", "low").
 * Set once on first launch; `None` for existing installs (treated as High).
 */
deviceTier?: string | null;
/**
 * Enable work-hours schedule (when false, records 24/7 as usual)
 */
scheduleEnabled?: boolean;
/**
 * Per-day schedule rules (only used when schedule_enabled is true)
 */
scheduleRules?: ScheduleRule[];
/**
 * Require authentication for remote (non-localhost) API access.
 */
apiAuth?: boolean;
/**
 * Custom API key for remote authentication. If empty, a key is auto-generated.
 */
apiKey?: string;
/**
 * When true, the HTTP server binds to `0.0.0.0` so other devices on the
 * LAN can reach the screenpipe API. Off by default — the server binds
 * `127.0.0.1` (localhost only) which is the safe choice.
 *
 * `api_auth` is force-enabled whenever this is true; [`RecordingConfig::from_settings`]
 * overrides it, so a user can't accidentally expose the API unauthenticated on their network.
 */
listenOnLan?: boolean }) &
/**
 * Catch-all for fields added by the frontend (e.g. chatHistory)
 * that the Rust struct doesn't know about. Without this, `save()` would
 * serialize only known fields and silently wipe frontend-only data.
 */
({ [key in string]: null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue } }) & { aiPresets: AIPreset[]; isLoading: boolean; devMode: boolean; ocrEngine: string; dataDir: string; embeddedLLM: EmbeddedLLM; autoStartEnabled: boolean; platform: string; disabledShortcuts: string[]; showScreenpipeShortcut: string; startRecordingShortcut: string; stopRecordingShortcut: string; startAudioShortcut: string; stopAudioShortcut: string; showChatShortcut: string; searchShortcut: string; lockVaultShortcut?: string; showShortcutOverlay?: boolean;
/**
 * Overlay size: "small" (default), "medium" (1.5x), "large" (2x)
 */
shortcutOverlaySize?: string;
/**
 * Unique device ID for AI usage tracking (generated on first launch)
 */
deviceId?: string;
/**
 * Timeline overlay mode: "fullscreen" (floating panel above everything) or
 * "window" (normal resizable window with title bar).
 */
overlayMode?: string;
/**
 * Allow screen recording apps to capture the overlay.
 * Disabled by default so the overlay doesn't appear in screenpipe's own recordings.
 */
showOverlayInScreenRecording?: boolean;
/**
 * When true, the chat window stays above all other windows (default: true).
 */
chatAlwaysOnTop?: boolean;
/**
 * Show restart notifications when audio/vision capture stalls.
 * Disabled by default for now until the stall detector is more reliable.
 */
showRestartNotifications?: boolean;
/**
 * When true, apply macOS vibrancy effect to the sidebar for a translucent look.
 */
translucentSidebar?: boolean;
/**
 * When true (default), hide model "thinking" reasoning blocks in the chat
 * transcript. The model still emits them server-side; we just don't
 * render the collapsible block in the UI.
 */
hideThinkingBlocks?: boolean;
/**
 * UI theme: "light", "dark", or "system".
 */
uiTheme?: string;
/**
 * Windows-only: when true, clicking the X on the Home window hides it to
 * the system tray (and removes it from the taskbar) instead of minimizing.
 * Read by the CloseRequested handler in main.rs. Default off (historical
 * minimize-to-taskbar behavior).
 */
minimizeToTrayOnClose?: boolean }
export type ShowRewindWindow = "Main" | { Home: { page: string | null } } | { Search: { query: string | null } } | "Onboarding" | "Chat" | "PermissionRecovery"
export type Suggestion = { text: string;
/**
 * Short preview with real data (e.g. "1h20m in VS Code — auth.rs, api.rs")
 */
preview?: string | null;
/**
 * Priority: 1 = hero card (most relevant), 2+ = supporting cards
 */
priority?: number }
export type ViewerContent = { kind: "text"; text: string; name: string; path: string; truncated: boolean; total_bytes: number } | { kind: "image"; data_url: string; name: string; path: string } |
/**
 * Non-text, non-image file (random binary). The UI surfaces a
 * polite "open in default app" prompt instead of rendering bytes
 * as garbled text.
 */
{ kind: "binary"; name: string; path: string; total_bytes: number } | { kind: "error"; message: string; path: string }
/**
 * Custom vocabulary entry for transcription biasing and word replacement.
 */
export type VocabEntry = {
/**
 * The word or phrase to bias toward during transcription.
 */
word: string;
/**
 * Optional replacement — if set, the transcribed `word` is replaced with this.
 */
replace_with?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
